sudo: required
services:
  - docker

env:
  - COMPOSE_VERSION=1.5.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker pull unblibraries/nginx-php:alpine
  - 'sed -i "s|image: unblibraries/nginx-php:alpine|build: .|g" docker-compose.yml'
  - 'echo "  volumes:" >> docker-compose.yml'
  - 'echo "    - ./travis/htdocs:/app/html" >> docker-compose.yml'

script:
  - docker-compose build
  - docker-compose up -d
  - travis/waitForNginxlDeploy.sh
  - travis/testPHP.sh

after_success:
  - travis/triggerDockerHubBuild.sh

notifications:
  slack:
    secure: cQVNyyCZn5x2HHVuNdjbFYuxZ1Pxy4Wf7ZbYeNFnoAKTn7wVGb88Bwu+/T5s+rxLCGteCjx76kQN7UkyGDaQpp1MdZ33knxfAJldeSESDjba/zdYSJGlYKpxtSogUaL5WmobJXqNRaKxpdUgUNMC8rfitcA9t6Q713r3xHivvkZAXap/HjTCzvA6IrW6fRi8nqs0h8V4FdmvvqHCj81yHRSCIdxkJKGXiK1xBP1uZTGtQ5MuWtBXs023UzDHX3SRoj8mRIVq6+qaydUdSkZG7hpK7KOmP7R50WR2/Y6zwNg7e5R5JDzHGB8eQM0o4r4VyAkp7O0YlW6HqZXUk5wlAZo6m6yzOktjMKKH3QB1Cr6lokOxlSvLs1/P8dtEurO8kTfRK+1BxunK/0plTNRvAV9+RsGnWzWPR4mx3iehIOPdRn0y7vzagAEeMbGjItvXnSG9qy+VT1MiuxgLOI4UL74i6n4kwnGGawEEaKtZQApaRsGYDVW2MKplakaaus5AIEGB6yR+gxOq+czaDyQ5Ct+wOjOG0k7ocRNmjq9QD9wrqBd14B+Pm9vT1RRiPHgUOuTGX5cQkNLkuP8fr1PT+NS0ruUVK1DldN5qMFZuA6RuOYfFnSgIqOyT5wkVxW+jWxEi84h3Pnn13jwW/mGRDsqrah9D0oM2g+HptQoUsH8=
